# Generated by Django 3.0.9 on 2020-08-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200804_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='max_bid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_bids',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
