# Generated by Django 3.0.9 on 2020-08-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200806_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='number_of_bids',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
