# Generated by Django 3.0.9 on 2020-08-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200810_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category_belongs',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
