# Generated by Django 3.0.9 on 2020-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ncomments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
