# Generated by Django 3.0.9 on 2020-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200815_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_owner_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
